<html>
 <head>
  <title>Bienvenido a Cinema</title>
  {{ stylesheet_link('css/bootstrap.min.css') }}
  {{ javascript_include('js/bootstrap.min.js') }}
 </head>
 <body>
 <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="container-fluid">
         <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
             </button>
         <h1>Bienvenido a Cinema</h1>
             <p>Cinema te permite llevar un registro de tus peliculas, los actores y directores asociados a estasy mucho mas!</p>
             <ul class="nav navbar-nav">
                 <li><a href="{{ url('peliculas') }}">Peliculas</a></li>
         <li><a href="{{ url('actores') }}">Actores</a></li>
         <li><a href="{{ url('directores') }}">Directores</a></li>
         <li><a href="{{ url('generos') }}">Generos</a></li>
         <li><a href="{{ url('idiomas') }}">Idiomas</a></li>
         <li><a href="{{ url('nationality') }}">Nacionalidad</a></li>
             </ul>
         </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="navbarCollapse">
             
         </div>
     </div>
 </nav>
<div class="container-fluid" style="margin-top:100px">

<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["idiomas/index", "Volver"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["idiomas/new", "Crear nuevo "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Resultados de la busqueda de Idiomas</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Idioma</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $idioma): ?>
            <tr>
                <td><?php echo $idioma->id ?></td>
            <td><?php echo $idioma->idioma ?></td>

                <td><?php echo $this->tag->linkTo(["idiomas/edit/" . $idioma->id, "Editar"]); ?></td>
                <td><?php echo $this->tag->linkTo(["idiomas/delete/" . $idioma->id, "Eliminar"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("idiomas/search", "Primero") ?></li>
                <li><?php echo $this->tag->linkTo("idiomas/search?page=" . $page->before, "Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("idiomas/search?page=" . $page->next, "Siguiente") ?></li>
                <li><?php echo $this->tag->linkTo("idiomas/search?page=" . $page->last, "Ultimo") ?></li>
            </ul>
        </nav>
    </div>
</div>
<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["generos", "Volver"]) ?></li>
        </ul>
    </nav>
</div>
</div>
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <footer>
                <p>&copy; Cinema te permite llevar un registro de tus peliculas, los actores y directores asociados a estasy mucho mas! </p>
            </footer>
        </div>
    </div>
</div>